.travis.yml, README.md
This updates travis to test all channels, and a pinned minimum version too (arbitrarily picked to match our other coreos projects). It also refreshes the README.
=> travis: build all channels and a minimum version too

src/header.rs, src/partition.rs, tests/test.rs
This cleans up a few warnings, as reported by current Rust stable
toolchain (1.27).
=> gpt: clean up warnings

Cargo.toml, tests/test.rs
This updates all dependencies to their latest versions. `simplelog` is only used in tests, thus moved to `dev-dependencies` section.
=> cargo: update dependencies to latest version

src/header.rs, src/partition.rs, src/partition_types.rs, tests/test.rs
This adds [well-known](https://coreos.com/os/docs/latest/constants-and-ids.html#gpt-partition-types) GUIDs for coreos disks.
The second commit here is pretty large, but contains only the result of a `cargo fmt` on the whole project, so that further changes can be easily formatted without spurious/noisy deltas.
=> partition-types: add CoreOS GUIDs 

.travis.yml, src/header.rs, src/partition.rs
This fixes all warnings currently reported by clippy.
It also sets up a dedicated pass on travis to perform automatic CI
linting via clippy.
=> gpt: clean all clippy warnings and add to travis checks

examples/inspect.rs, src/disk.rs, src/header.rs, src/lib.rs, src/partition.rs
This introduces a new high-level API to work with a disk device/image
as a whole.
`GptDisk` builds upon the existing low level partitions and headers
primitives but provides a way to split in-memory GPT
layouts manipulation and persisting changes to disk, while ensuring
metadata coherence.
=> gpt: introduce an high-level disk API

src/header.rs, src/lib.rs, src/partition.rs, tests/test.rs
This removes all hardcoded sectore size values and plumbs through
the external configuration setting.
=> header: remove 512B sector size assumptions

README.md, src/disk.rs, src/header.rs, src/lib.rs, src/partition.rs, tests/gpt.rs, tests/test.rs
This exposes methods for customizing and retrieving sector size on a GPT disk object.
The PR also carries misc fixes/enhancements to docs and test that I happened to touch while looking around.
=> disk: expose sector size setting

src/lib.rs
This changes all methods which can be part of the builder chain to
take mutable self.
=> gpt/config: take mutable self everywhere

src/partition.rs, tests/gpt.rs, tests/test.rs
This fixes how a partition entry is encoded into raw bytes, to be
written as part of a partition table. It also adds support for
variable sized entries (as set in the disk header).
=> partition: fix partition entry serialization

src/partition.rs, tests/gpt.rs
This adds a few methods to help reading, seeking, and manipulating
partition content. All helpers are LB-size aware and covered by tests.
=> partition: add lba-to-bytes translation helpers

Cargo.toml, src/header.rs, src/lib.rs, src/partition.rs, tests/gpt.rs
This adds support for writing the backup header for a GPT disk.
It also performs a general cleanup of crate/use directives.
=> header: support writing backup header

src/header.rs, src/lib.rs, src/partition.rs
This adds documentation to all public items and turns on warning to
make sure all future API will come with docstrings.
=> gpt: document all public APIs

src/mbr.rs, tests/mbr.rs
This adds readers and writers for few specific legacy-BIOS bits
(bootcode and disk-signature) which are not GPT-specific but may be
interesting for consumers.
=> mbr: support reading/writing some legacy-BIOS bits

Cargo.toml, src/lib.rs, src/partition.rs, src/partition_types.rs, tests/gpt.rs, tests/test.rs
Quyzi and I worked together on creating this PR that changes all the partition uuid's into constants.  This should make it easier for people using the library to identify which partition type they'd like.  
I tried to come up with a macro that would eliminate all the match statements but I couldn't quite get the compiler to accept it.  So for now all the uuid's are hard coded in the match statements though in the future I'd love for anyone to take a crack at eliminating that code.  
Inspiration for this PR came from the http library which takes a s similar approach to exposing library constants.  
Some possible improvements could be adding flexibility to the OperatingSystem and Type parsers to allow custom input like the http library does.
=> Partition type macro

src/disk.rs, src/lib.rs
I've changed the add_partition function slightly to return the
partition id.  Makes it easier to identify the partition that was
added later.  I also made the size specified be in bytes and noted
that in the docs.
=> Small tweaks to add partition

src/header.rs, src/lib.rs, src/partition.rs, src/partition_types.rs, tests/gpt.rs, tests/test.rs
The partition id returned from creating partitions was always wrong.  Partition id's start at one and not zero.  This patch fixes that.  It uses a BTreeMap to maintain sorted order of the partitions.
=> Fix bug in partition id creation

src/header.rs, src/macros.rs, src/partition.rs, tests/gpt.rs
The file_read_partitions function creates partitions for empty partition array entries.  This commit skips over the empty partition entries
=> Fixed file_read_partitions so that it skips unused partition entries

src/header.rs, src/partition.rs
Changes some internal functions from taking a `File` to taking a `Read + Write` (or `Read + Write + Seek` when writing is required), and adds functions (`file_read_partitions` and `read_header_from_arbitrary_device`) to read the header and partitions from a `Read + Seek` device.
=> Add the minimal necessary support required to read from Read + Seek devices

src/header.rs, src/lib.rs, tests/fixtures/gpt-headers.txt, tests/fixtures/test-headers.txt
When writing to disk header, give old header (if exists) to compute new to keep the first_usable and last_usable attributes so as to not break the GPT (partprobe will complaing about not using all space available.  Especially since the first_usable is not always sector 34.  In fact, it is usually 2048 in order to align partition boundaries. Otherwise, if the original headers are not given, use the default values.
Also, fix getting the next partition number so that it gets the first USABLE partition number, NOT the next highest partition number, and fix find_free_sectors so that if creating a partition, it can start from the first usable sector (aka 2048 usually, this starts the partition at the physical sector boundary so a blank disk getting partitioned won't complain about not starting …
=> Take into account old disk header values when computing new header

src/partition.rs
Realized this when gpt was returning "BOOTry" for the partition name where parted and everything else just shows "BOOT".
=> The partition names are null-terminated.

.travis.yml, README.md, src/disk.rs, src/header.rs, src/lib.rs, src/macros.rs, src/mbr.rs, src/partition.rs, src/partition_types.rs, tests/gpt.rs
Builds on the work done in Quyzi#51. The primary enhancement in this PR is that `GptDisk`, `Partition`, and `ProtectiveMBR` can now work with anything that implements the `Read + Write + Seek + Debug` traits, instead of just a `File`.
It also greatly improves compatibility of GPT partition tables that are created from scratch (rather than modifying an existing GPT partition table in a previous device/image file), e.g., the partition array on disk will be at least 128 entries and unused entries are zero-filled. 
New tests were added to exercise the new generic device support (e.g., writing/reading to/from a memory buffer) as well as creating a GPT table completely from scratch. A test was also added that if we write what we read from an existing disk image and then read it back, that we …
=> Support for arbitrary devices & other various enhancements

Cargo.toml, src/header.rs, src/partition.rs
Update the crate to 2.0.0 because of the size of the last update. Also updating the dependencies for `uuid`, `simplelog`, and `tempfile`
=> Update version of the crate and dependencies

src/header.rs, src/lib.rs
Allow for creating custom partition tables with sizes other than 128. Also allows changing the number of partitions entries in existing tables.
=> Allow for creating and modifying custom partition tables

src/partition.rs, src/partition_types.rs
If the partition type is not known then lets make it resort to a default value instead of crashing.
My Android device seems to have a partition type which isn't in the list of known types.
=> Don't crash on unknown partition types.

examples/inspect.rs, src/disk.rs, src/header.rs, src/lib.rs, src/partition.rs
When trying to store `GptDisk` in a struct which was created from a `Path` the following error occurs.
```rust
error[E0597]: `path` does not live long enough
--> src/main.rs:240:10
|
238 |           let disk = GptConfig::new()
|  ____________________-
239 | |             .writable(false)
240 | |             .open(&path)?;
| |___________________^^^^^- argument requires that `path` is borrowed for `'static`
|                     |
|                     borrowed value does not live long enough
...
243 |       }
|       - `path` dropped here while still borrowed
```
Making `GptDisk<'static>` the return type fixes this.
Additionally i propose to update the parameter `Path` to also accept a `str` like the std library does.
=> Relax `Path` parameter to `impl AsRef<Path>`

Cargo.toml, src/header.rs, src/macros.rs, src/partition.rs, src/partition_types.rs
**Provides:**  
Support to specify and read partition UUID that are not hardcoded in the library
**Motivation:**  
I am writing a tool that needs to handle gpt in the most general way possible, I can't really limit myself to a few partition types.
**How:**  
The problem is `partition_type::Type`, which contains `pub guid: &'static str,`.  
This can't support anything non-hardcoded. The solution is either to keep trying to use `&str` and play around with lifetimes and hide allocations somewhere in ugly ways, or just use `String`
At that point the macro is modified so that instead of generating `const NAME : Type` it generates `fn NAME() -> Type` which allocates the string for the guid on the heap.
The macro will return a Type as before, but when called with an unknown UUID it will set the …
=> Support custom partition GUIDs

src/lib.rs
Add take_disk method to reclaim GptDisk's underlying device.
=> Add take_disk method

src/disk.rs, src/partition.rs
This mixes a few things:
* Take partition length being an inclusive range into account (fixes #96)
* Rename size to sectors_len: This makes it consistent with bytes_len naming and more clear of what it returns
* Make bytes_len use sectors_len for the calculation rather then re-implementing it
* Expand partition len tests to test for both sectors and byte length
=> Fix and improve sector length calculation

src/lib.rs, tests/gpt.rs
calculate sector alignment based on the current partitions
in order to promise uniform alignment
return 0 if no partitions existed
return 1 if partitions are not well aligned ( can be seen as 1 alignment )
MAX ALIGNMENT IS 2048 ! And the result is ok ONLY if existed partitions is well aligned
=> Calculate existed alignment

src/macros.rs, src/partition_types.rs
This does make Type::from_name() kind of redundant. Since now the input will be uppercased twice.
Could remove uppercase call in from_name(), but not sure how you want to handle that change from a logging perspective.
=> Make partition_types::Type::FromStr case-insensitive for guid
